[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    fastled/FastLED @ ^3.6.0
    madhephaestus/ESP32Servo @ ^0.13.0
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/cu.usbserial-1420
monitor_port = /dev/cu.usbserial-1420
board_build.flash_mode = dio
